name: HPE - Deploy Staging Environments

on: [push, workflow_dispatch]

jobs:
  stage-vrt-job:
    uses: hse-aurora/keylime-ci/.github/workflows/gcp-deploy.yml@main
    with:
      vrt_repo: ${{ github.repository }}
      vrt_ref: ${{ github.ref }}
      a_repo: hse-aurora/rust-keylime-fork
      a_ref: master
      gcp_id: stage-vrt
      overwrite_vm: true
    secrets:
      SSH_KEYLIME_CI_DEPLOY_KEY: ${{ secrets.SSH_KEYLIME_CI_DEPLOY_KEY }}
  stage-vrta-job:
    uses: hse-aurora/keylime-ci/.github/workflows/gcp-deploy.yml@main
    with:
      vrt_repo: ${{ github.repository }}
      vrt_ref: ${{ github.ref }}
      a_repo: hse-aurora/rust-keylime-fork
      a_ref: internal
      gcp_id: stage-vrta
      overwrite_vm: true
    secrets:
      SSH_KEYLIME_CI_DEPLOY_KEY: ${{ secrets.SSH_KEYLIME_CI_DEPLOY_KEY }}